### ISSUE TITLE
Oxide Not Running After Server/Docker Restart

### ISSUE THREAD

**Issue by seventhaxis** [mdarkness1988/Rust-Server#10]
Oxide/uMod will not execute following a server restart. I have tried only using the server commands via console as well as outright restarting the docker container. The initial bootup works fine, creating the necessary folders and allowing me to add and activate plugins. However, when restarting the server or container, oxide simply isn't loaded.

**What are you running on (please complete the following information):**
 - OS: Linux 4.18.20-unRAID (6.6.6)
 - Browser: N/A
 - Hardware: Intel® Xeon® CPU E5-2670 0 @ 2.60GHz (x2), 64 GB ECC RAM

**Additional information:**
Consistently happens on docker restart or via server commands within RCON console.

**Comment by seventhaxis** [comment]
Closing issue. No response from docker maintainer.

**Comment by StuDaBaiker** [comment]
This was resolved in the latest update
