### ISSUE TITLE
Can we run multi instances of this docker?  I would like to get another server going

### ISSUE THREAD

**Issue by bobbart** [mdarkness1988/Rust-Server#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bobbart** [comment]
Can we run multi instances of the docker?  I would like to get another server up.

**Comment by mdarkness1988** [comment]
https://github.com/mdarkness1988/Rust-Server/issues/7

**Comment by mdarkness1988** [comment]
Close due to inactive
