### ISSUE TITLE
Mod/Permissions Issue

### ISSUE THREAD

**Issue by StuDaBaiker** [mdarkness1988/Rust-Server#17]
**Describe the issue you are having**
Answer:
Every time the server starts after the initial install oxide will not run.

**What was you doing before it happened**
Answer:
Server is shut down nightly for appdata backup, requires manual intervention to get running again.

**What are you running on (please complete the following information):**
 - OS: Unraid

**Additional information**
Have found a way to get it working but it requires manual work every day after the server is shut down for backups.

Server will start normally after a reboot, but nothing in the oxide folder will run, and the RustIO map plugin that is located in the RustDedicated_Data/Managed folder will not run.

I believe the permissions are changing so the server can't see the files on startup. I've tried to only set new permissions on the oxide and Managed folders with no luck. 

However if I run `newperms /mnt/cache/appdata/Rust-Server/` and delete all the files that aren't in folders in the Rust-Server directory it will work. I think the files need to be deleted because newperms doesn't set the correct permissions for them. If I try to set permissions and run it will say it doesn't have permission to access RustDedicated. 

Hopefully this can be resolved, its super annoying and I saw someone else was having the same issue but didn't receive a response. Hopefully the troubleshooting and steps make it easy to find and fix. I feel like I'm pretty close to finding the workaround but if I have any more issues with this I'm about to give up on Rust.

**Comment by mdarkness1988** [comment]
Hi. Thank you for you input. That is strange and will see what I can do but that sounds like a os unraid permission issue rather then the rust coding itself.

Any updates please let me know. I will still look into this for you.

**Comment by StuDaBaiker** [comment]
I was able to work on this a bit today and was able to narrow it down to a specific file. It has nothing to do with the permissions, if I delete `Rust-Server\Compiler.x86_x64` everything works correctly after it downloads the file again.

**Comment by mdarkness1988** [comment]
That's strange. Must of installed it incorrectly the first time.
Has it been working ever since?

**Comment by StuDaBaiker** [comment]
No, the file has to be deleted every time it is shut down

**Comment by mdarkness1988** [comment]
So no access to that file is the issue?

**Comment by mdarkness1988** [comment]
I set that file as following (chmod +x)
And the folder of the file as chmod -R 777

**Comment by StuDaBaiker** [comment]
No permissions stay the same. Before and after show read, write, and executable for root user.
`-rwx------ 1 root   root   4149004 Jul 14 10:58 Compiler.x86_x64*`

The server will run after a reboot, oxide never starts and neither does the RustIO map which is located in `Rust-Server/RustDedicated_Data/Managed`

**Comment by StuDaBaiker** [comment]
I tried a graceful shutdown as well in case being force closed by the backup was corrupting the file but it does the same thing.

**Comment by mdarkness1988** [comment]
So if I tell it to delete the file and install it on every startup with everything work as normal just for a temp fix?

**Comment by StuDaBaiker** [comment]
That should do the trick

**Comment by mdarkness1988** [comment]
Please confirm an update has been released to fix this error?

**Comment by StuDaBaiker** [comment]
The update is available, I will test it out when I'm home from work

**Comment by StuDaBaiker** [comment]
I think there might be a typo in the update. I'm getting a syntax error now and it won't run at all.

`./start.sh: line 64: syntax error near unexpected token `fi'`

**Comment by mdarkness1988** [comment]
Hoping it's fixed now lol.

**Comment by StuDaBaiker** [comment]
Running like a champ! Is there any way to use a map from a previous version?

**Comment by StuDaBaiker** [comment]
Thanks so much for the help! Much appreciated!

**Comment by mdarkness1988** [comment]
Glad to help. Sorry took so long
