### ISSUE TITLE
Error in /apps/rcon_app/app.js

### ISSUE THREAD

**Issue by E-Coombs** [mdarkness1988/Rust-Server#5]
Hey there are two syntax errors in the app.js script.

Line 28: consol.log("Rcon Connected to" + serverHostname + ":" + serverPort + "/" + serverPassword)
Line 54: consol.log("Message not sent")

Changing these to console.log() fix unraid -> rcon commands

**Comment by mdarkness1988** [comment]
What told you that there are syntax errors?

**Comment by E-Coombs** [comment]
When i tried to send an rcon command, the error stated that consol does not exist. Its just a typing mistake.
