### ISSUE TITLE
second rust server ?

### ISSUE THREAD

**Issue by taobyebye** [mdarkness1988/Rust-Server#7]
Hi,

when i create a second rust server, it doesnt work.
Set other file location and other Ports for rcon and rust, but the server is untraceable and rcon get the message " Connection was closed - Error 1006 "

**Comment by mdarkness1988** [comment]
If you make a second instance you must select host mode to a custom IP address so that the ports don't conflict with each other.

But doing so will brake the auto port forwarding on that rust server so you must open the new ports manually on your router.

P.S don't use same ports as the other server.
I will try to simplify this in the near future but as of now this is the only way

**Comment by mdarkness1988** [comment]
Before you do that. Did you match the port numbers with the port forwarding numbers?

**Comment by taobyebye** [comment]
Yes i choose diffrent ports and open the ports manually on my router in the same way like the first server.
I have choose bridge as network, each instance has a own ip address

![r1](https://user-images.githubusercontent.com/44962130/49990129-df2b8900-ff7c-11e8-8d06-24273ded0524.PNG)

Server1:
![r2](https://user-images.githubusercontent.com/44962130/49990132-e2bf1000-ff7c-11e8-95ab-108560621e08.PNG)

Server2:
![r3](https://user-images.githubusercontent.com/44962130/49990133-e488d380-ff7c-11e8-8484-c65b87dc5cc6.PNG)

**Comment by mdarkness1988** [comment]
For web ports try 81 not 8090.
Use port 28016 instead of 28015
And port 28017 instead of 28016

So basically go 1 number on each and let me know.

Ideally select custom IP so say your host is 192.168.0.10
Then server 2 should be 192.168.1.10

**Comment by mdarkness1988** [comment]
Only change the port forwarding ports and leave the others default as that won't matter since it's on a new up address

**Comment by taobyebye** [comment]
now it works
with complete other ip address 
server 2 is now 192.168.1.50
ports a default, only rust port is other

**Comment by mdarkness1988** [comment]
Good to hear.
I will try make it simpler in the next few updates I make.

**Comment by taobyebye** [comment]
Unfortunately too early pleased
After a restart of the Container, 
![1](https://user-images.githubusercontent.com/44962130/50119286-9ca2ce80-0252-11e9-9e10-7c057f5500de.PNG)
sometimes it works, sometimes it doesn't.

**Comment by taobyebye** [comment]
Solved the problem first. If you change the port of an existing container, it does not work. You have to delete the container and create a new one. 
Let's see how long it lasts, or I'll get back to you
